test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,41 +48,41 @@ jobs:
 #      - name: Adapter npm test
 #        run: npm test
 #
-#      - name: Set up Docker Buildx
-#        uses: docker/setup-buildx-action@v3
-#
-#      - name: Login to ghcr.io
-#        uses: docker/login-action@v3
-#        with:
-#          registry: ghcr.io
-#          username: ${{ github.actor }}
-#          password: ${{ secrets.GITHUB_TOKEN }}
-#
-#      - name: Login to Docker Hub
-#        uses: docker/login-action@v3
-#        with:
-#          username: ${{ secrets.DOCKERHUB_USERNAME }}
-#          password: ${{ secrets.DOCKERHUB_TOKEN }}
-#
-#      - name: Set Docker tags
-#        run: |
-#          set -euxo pipefail
-#          case $GITHUB_EVENT_NAME in
-#            push)
-#              IMAGE_TAG=$GITHUB_REF_NAME
-#              ;;
-#            pull_request)
-#              IMAGE_TAG=$GITHUB_HEAD_REF
-#              ;;
-#            *)
-#              echo "ERROR: Unknown event"
-#              exit 1
-#              ;;
-#          esac
-#          export IMAGE_TAG=$(echo $IMAGE_TAG | sed 's/\//-/g' | sed 's/^v//')
-#          echo "PLATFORMS=linux/amd64" >> "$GITHUB_ENV"
-#          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
-#
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to ghcr.io
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Set Docker tags
+        run: |
+          set -euxo pipefail
+          case $GITHUB_EVENT_NAME in
+            push)
+              IMAGE_TAG=$GITHUB_REF_NAME
+              ;;
+            pull_request)
+              IMAGE_TAG=$GITHUB_HEAD_REF
+              ;;
+            *)
+              echo "ERROR: Unknown event"
+              exit 1
+              ;;
+          esac
+          export IMAGE_TAG=$(echo $IMAGE_TAG | sed 's/\//-/g' | sed 's/^v//')
+          echo "PLATFORMS=linux/amd64" >> "$GITHUB_ENV"
+          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
+
 #      - name: Docker build local
 #        run: |
 #          ## local build for scanners
