test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,103 +16,103 @@ jobs:
       - name: Checkout application repository
         uses: actions/checkout@v4
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '20'
-          registry-url: https://npm.pkg.github.com/
-          scope: '@owneraio'
-
-      - name: Finp2p-Contracts npm clean-install
-        working-directory: ./finp2p-contracts
-        run: npm clean-install
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Finp2p-Contracts npm run compile
-        working-directory: ./finp2p-contracts
-        run: npm run compile
-
-      - name: Finp2p-Contracts npm run test
-        working-directory: ./finp2p-contracts
-        run: npm run test
-
-      - name: Adapter npm clean-install
-        run: npm ci
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Adapter npm run build
-        run: npm run build
-
-      - name: Adapter npm test
-        run: npm test
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Login to ghcr.io
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Set Docker tags
-        run: |
-          set -euxo pipefail
-          case $GITHUB_EVENT_NAME in
-            push)
-              IMAGE_TAG=$GITHUB_REF_NAME
-              ;;
-            pull_request)
-              IMAGE_TAG=$GITHUB_HEAD_REF
-              ;;
-            *)
-              echo "ERROR: Unknown event"
-              exit 1
-              ;;
-          esac
-          export IMAGE_TAG=$(echo $IMAGE_TAG | sed 's/\//-/g' | sed 's/^v//')
-          echo "PLATFORMS=linux/amd64" >> "$GITHUB_ENV"
-          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
-
-      - name: Docker build local
-        run: |
-          ## local build for scanners
-          docker build \
-            --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
-            -t "ghcr.io/owneraio/finp2p-ethereum-adapter:${{ env.IMAGE_TAG }}" -f ./Dockerfile .
-      
-
-      - name: Trivy scan
-        run: |
-          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
-      
-          ## trivy scan on local images
-          trivy image "ghcr.io/owneraio/finp2p-ethereum-adapter:${{ env.IMAGE_TAG }}"
-#          trivy image "ghcr.io/owneraio/hardhat:${{ env.IMAGE_TAG }}"
-#          trivy image "ghcr.io/owneraio/finp2p-contracts:${{ env.IMAGE_TAG }}"
-
-      - name: Adapter Build and push
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          push: true
-          sbom: false
-          provenance: false
-          file: ./Dockerfile
-          build-args:
-            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
-          tags: |
-            ownera/finp2p-ethereum-adapter:${{ env.IMAGE_TAG }}
-            ghcr.io/owneraio/finp2p-ethereum-adapter:${{ env.IMAGE_TAG }}
+#      - name: Setup Node.js
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: '20'
+#          registry-url: https://npm.pkg.github.com/
+#          scope: '@owneraio'
+#
+#      - name: Finp2p-Contracts npm clean-install
+#        working-directory: ./finp2p-contracts
+#        run: npm clean-install
+#        env:
+#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Finp2p-Contracts npm run compile
+#        working-directory: ./finp2p-contracts
+#        run: npm run compile
+#
+#      - name: Finp2p-Contracts npm run test
+#        working-directory: ./finp2p-contracts
+#        run: npm run test
+#
+#      - name: Adapter npm clean-install
+#        run: npm ci
+#        env:
+#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Adapter npm run build
+#        run: npm run build
+#
+#      - name: Adapter npm test
+#        run: npm test
+#
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@v3
+#
+#      - name: Login to ghcr.io
+#        uses: docker/login-action@v3
+#        with:
+#          registry: ghcr.io
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Login to Docker Hub
+#        uses: docker/login-action@v3
+#        with:
+#          username: ${{ secrets.DOCKERHUB_USERNAME }}
+#          password: ${{ secrets.DOCKERHUB_TOKEN }}
+#
+#      - name: Set Docker tags
+#        run: |
+#          set -euxo pipefail
+#          case $GITHUB_EVENT_NAME in
+#            push)
+#              IMAGE_TAG=$GITHUB_REF_NAME
+#              ;;
+#            pull_request)
+#              IMAGE_TAG=$GITHUB_HEAD_REF
+#              ;;
+#            *)
+#              echo "ERROR: Unknown event"
+#              exit 1
+#              ;;
+#          esac
+#          export IMAGE_TAG=$(echo $IMAGE_TAG | sed 's/\//-/g' | sed 's/^v//')
+#          echo "PLATFORMS=linux/amd64" >> "$GITHUB_ENV"
+#          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
+#
+#      - name: Docker build local
+#        run: |
+#          ## local build for scanners
+#          docker build \
+#            --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
+#            -t "ghcr.io/owneraio/finp2p-ethereum-adapter:${{ env.IMAGE_TAG }}" -f ./Dockerfile .
+#
+#
+#      - name: Trivy scan
+#        run: |
+#          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
+#
+#          ## trivy scan on local images
+#          trivy image "ghcr.io/owneraio/finp2p-ethereum-adapter:${{ env.IMAGE_TAG }}"
+##          trivy image "ghcr.io/owneraio/hardhat:${{ env.IMAGE_TAG }}"
+##          trivy image "ghcr.io/owneraio/finp2p-contracts:${{ env.IMAGE_TAG }}"
+#
+#      - name: Adapter Build and push
+#        uses: docker/build-push-action@v5
+#        with:
+#          context: .
+#          push: true
+#          sbom: false
+#          provenance: false
+#          file: ./Dockerfile
+#          build-args:
+#            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
+#          tags: |
+#            ownera/finp2p-ethereum-adapter:${{ env.IMAGE_TAG }}
+#            ghcr.io/owneraio/finp2p-ethereum-adapter:${{ env.IMAGE_TAG }}
 
 
       - name: Docker-deploy Build and push
@@ -123,7 +123,7 @@ jobs:
           sbom: false
           provenance: false
 
-          file: ./Dockerfile-deploy
+          file: ./finp2p-contracts/Dockerfile-deploy
           build-args:
             GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
           tags: |
